local ActionType      = require( "parser_generator.action_type" )
local RuntimeTemplate = require( "parser_generator.runtime_template" )

---@class CodeGenerator
---@field parserGenerator ParserGenerator
local CodeGenerator = {}
CodeGenerator.__index = CodeGenerator
CodeGenerator.__type = "CodeGenerator"

--- Creates a new CodeGenerator wrapping a fully-generated ParserGenerator.
---@param parserGenerator ParserGenerator
---@return CodeGenerator
function CodeGenerator.new( parserGenerator )
    local codeGenerator = setmetatable( {}, CodeGenerator )
    codeGenerator.parserGenerator = parserGenerator
    return codeGenerator
end

--- Escapes a string for embedding as a double-quoted Lua string literal.
---@param s string
---@return string
---@return number
local function escapeString( s )
    return s
        :gsub( "\\", "\\\\" )
        :gsub( '"',  '\\"'  )
        :gsub( "\n", "\\n"  )
        :gsub( "\r", "\\r"  )
        :gsub( "%z", "\\0"  )
end

--- Serializes the LEXER_RULES table into Lua source lines.
---@param grammar Grammar
---@param out string[]
local function emitLexerRules( grammar, out )
    table.insert( out, "local LEXER_RULES = {" )

    for _, lexerRule in ipairs( grammar.lexerRules ) do
        -- Skip the internal EOF sentinel (empty pattern, isSkipped = true)
        if lexerRule.token.name ~= "EOF" then
            table.insert( out, string.format(
                '    { pattern = "%s", token = "%s", skip = %s },',
                escapeString( lexerRule.pattern ),
                escapeString( lexerRule.token.name ),
                tostring( lexerRule.isSkipped )
            ) )
        end
    end

    table.insert( out, "}\n" )
end

--- Serializes the ACTION table (terminal actions) into Lua source lines.
---@param stateManager StateManager
---@param out string[]
local function emitActionTable( stateManager, out )
    table.insert( out, "local ACTION = {" )

    for _, state in ipairs( stateManager.states ) do
        local entries = {}

        for symbol, action in pairs( state.actions ) do
            if symbol.isTerminal then
                local entry

                if action.type == ActionType.SHIFT then
                    entry = string.format(
                        '        ["%s"] = { type = "shift", state = %d },',
                        escapeString( symbol.name ),
                        action.state.id
                    )
                elseif action.type == ActionType.REDUCE then
                    entry = string.format(
                        '        ["%s"] = { type = "reduce", lhs = "%s", len = %d },',
                        escapeString( symbol.name ),
                        escapeString( action.production.rule.left.name ),
                        #action.production.rule.right
                    )
                elseif action.type == ActionType.ACCEPT then
                    entry = string.format(
                        '        ["%s"] = { type = "accept" },',
                        escapeString( symbol.name )
                    )
                end

                if entry then
                    table.insert( entries, entry )
                end
            end
        end

        if #entries > 0 then
            table.insert( out, string.format( "    [%d] = {", state.id ) )
            for _, e in ipairs( entries ) do
                table.insert( out, e )
            end
            table.insert( out, "    }," )
        end
    end

    table.insert( out, "}\n" )
end

--- Serializes the GOTO table (non-terminal shift actions) into Lua source lines.
---@param stateManager StateManager
---@param out string[]
local function emitGotoTable( stateManager, out )
    table.insert( out, "local GOTO = {" )

    for _, state in ipairs( stateManager.states ) do
        local entries = {}

        for symbol, action in pairs( state.actions ) do
            if not symbol.isTerminal and action.type == ActionType.SHIFT then
                table.insert( entries, string.format(
                    '        ["%s"] = %d,',
                    escapeString( symbol.name ),
                    action.state.id
                ) )
            end
        end

        if #entries > 0 then
            table.insert( out, string.format( "    [%d] = {", state.id ) )
            for _, e in ipairs( entries ) do
                table.insert( out, e )
            end
            table.insert( out, "    }," )
        end
    end

    table.insert( out, "}\n" )
end

--- Generates and returns the complete Lua source for the parser.
---@return string
function CodeGenerator:emit()
    local parserGenerator = self.parserGenerator
    local out = {}

    table.insert( out, "-- Generated parser" )
    table.insert( out, "-- Source: " .. parserGenerator.inputFile )
    table.insert( out, "-- Generated by lua_parser_generator\n" )

    emitLexerRules( parserGenerator.grammar, out )
    emitActionTable( parserGenerator.stateManager, out )
    emitGotoTable( parserGenerator.stateManager, out )

    table.insert( out, RuntimeTemplate )

    return table.concat( out, "\n" )
end

return CodeGenerator
